FROM node:20-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

# Install dependencies (node_modules will be overridden by the anonymous volume trick)
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 5173
CMD ["pnpm", "run", "dev"]
